language: objective-c 
podfile: EVReflection/Podfile
osx_image: xcode611

before_install: 
- gem install cocoapods --pre
- export LANG=en_US.UTF-8
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
- xctool clean build -project EVReflection/EVReflection.xcodeproj -scheme EVReflectionTests -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO

