language: objective-c
podfile: AppMessage/Podfile
osx_image: xcode611

before_install: 
- gem install cocoapods --pre
- export LANG=en_US.UTF-8
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi



script:
- xctool clean build -workspace AppMessage/AppMessage.xcworkspace -scheme AppMessage -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO
